In [8]:
import torch as t
import einx

a = t.arange(16).view(4, 4).float()
a[:, 1] = 3
b = t.nn.functional.softmax(a, dim=-1)
a, b

(tensor([[ 0.,  3.,  2.,  3.],
         [ 4.,  3.,  6.,  7.],
         [ 8.,  3., 10., 11.],
         [12.,  3., 14., 15.]]),
 tensor([[2.0593e-02, 4.1362e-01, 1.5216e-01, 4.1362e-01],
         [3.4671e-02, 1.2755e-02, 2.5619e-01, 6.9639e-01],
         [3.5111e-02, 2.3657e-04, 2.5944e-01, 7.0522e-01],
         [3.5119e-02, 4.3340e-06, 2.5950e-01, 7.0538e-01]]))

In [10]:
a_ = einx.rearrange("a b -> a b c", a, c=a.shape[-1])
a_diff = a_ - einx.rearrange("a b c -> a c b", a_)
a_diff.shape

torch.Size([4, 4, 4])

In [14]:
a_diff_exp = a_diff.exp()
1 / a_diff_exp.sum(-2)

tensor([[2.0593e-02, 4.1362e-01, 1.5216e-01, 4.1362e-01],
        [3.4671e-02, 1.2755e-02, 2.5619e-01, 6.9639e-01],
        [3.5111e-02, 2.3657e-04, 2.5944e-01, 7.0522e-01],
        [3.5119e-02, 4.3340e-06, 2.5950e-01, 7.0538e-01]])

In [1]:
from zonotope.zonotope import Zonotope
from zonotope.functional import softmax

z = Zonotope.from_values([1, 2, 3], [[1, 0], [0, 1], [0, 0]])

r = softmax(z)

In [2]:
r.W_C

tensor([0.1498, 0.2959, 0.5045])

In [4]:
l, u = r.concretize()
l, u

(tensor([-0.6238, -0.3807,  0.0140]), tensor([0.9233, 0.9725, 0.9950]))