In [1]:
from zonotope.zonotope import Zonotope

z = Zonotope.from_values(
    [[1, 2, 3], [1.5, 1.25, 3]], [[[0, 0], [0, 0], [0, 0]], [[0, 1], [1, 0], [0, 1]]]
)
z.W_C.shape

ImportError: cannot import name 'Zonotope' from partially initialized module 'zonotope.zonotope' (most likely due to a circular import) (/home/sckathach/desktop/zonotopes/zonotope/zonotope.py)

In [2]:
from zonotope_nd.functional import tanh, exp, reciprocal, dot_product

r = dot_product(z, z, "a1 b, a2 b -> a1 a2")
r.W_C

tensor([[14.0000, 13.0000],
        [13.0000, 14.3125]], dtype=torch.float16)

In [3]:
r.W_Ei

tensor([[[0.0000, 0.0000, 0.0000],
         [2.0000, 4.0000, 0.0000]],

        [[2.0000, 4.0000, 0.0000],
         [2.5000, 9.0000, 1.5000]]], dtype=torch.float16)

In [6]:
import torch as t

(
    r.W_C.shape,
    r.W_Ei.shape,
    t.linalg.norm(r.W_Ei, ord=1, dim=-1).shape,
    t.linalg.norm(r.W_Es, ord=2, dim=-1).shape,
    r.W_Es.shape,
)

(torch.Size([2, 2]),
 torch.Size([2, 2, 3]),
 torch.Size([2, 2]),
 torch.Size([2, 2]),
 torch.Size([2, 2, 0]))

In [10]:
lr, ur = r.concretize()
lz, uz = z.concretize()
lr, ur, lz, uz

(tensor([[14.0000,  7.0000],
         [ 7.0000,  1.3125]], dtype=torch.float16),
 tensor([[14.0000, 19.0000],
         [19.0000, 27.3125]], dtype=torch.float16),
 tensor([[1.0000, 2.0000, 3.0000],
         [0.5000, 0.2500, 2.0000]], dtype=torch.float16),
 tensor([[1.0000, 2.0000, 3.0000],
         [2.5000, 2.2500, 4.0000]], dtype=torch.float16))

In [ ]:
import einx

einx.dot("a b, c b -> a c", z.W_C, z.W_C)

tensor([[14.0000, 13.0000],
        [13.0000, 12.8125]], dtype=torch.float16)

In [11]:
einx.dot("a b, c b -> a c", lz, lz)

tensor([[14.0000,  7.0000],
        [ 7.0000,  4.3125]], dtype=torch.float16)

In [12]:
einx.dot("a b, c b -> a c", uz, uz)

tensor([[14.0000, 19.0000],
        [19.0000, 27.3125]], dtype=torch.float16)

In [24]:
a = r.W_Ei
a[0, 0] = 2
a

tensor([[[ 2.0000,  2.0000,  2.0000],
         [-0.0000, -0.0000,  0.2407],
         [-0.0000, -0.0000,  0.1621]],

        [[-0.0000, -0.7998,  0.3054],
         [-1.7773, -0.0000,  0.8892],
         [-0.0000, -0.2476,  0.0000]]], dtype=torch.float16)

In [35]:
b = a.diagonal(dim1=-1, dim2=-2).sum(dim=[-1, -2])
b = a.diagonal(dim1=-1, dim2=-2).sum(dim=[-1])
b

tensor([2.1621, 0.0000], dtype=torch.float16)

In [29]:
c = a.sum(-1).sum(-1)

In [32]:
import torch as t

t.maximum(b - c, b + c, b - b, c - c)

TypeError: maximum() takes 2 positional arguments but 4 were given

In [39]:
a.view(-1, a.shape[-1]).shape

torch.Size([6, 3])

In [5]:
t.allclose(d, c)

True

In [1]:
pattern = "a b c, d e c -> a b d e"
a, bc = pattern.split(",")
b, c = bc.split("->")
a, b, c

('a b c', ' d e c ', ' a b d e')

In [4]:
a.strip().split(" "), b.strip().split(" ")

(['a', 'b', 'c'], ['d', 'e', 'c'])

In [8]:
a = 1, 2
a += (1, 2)

In [9]:
a

(1, 2, 1, 2)