In [21]:
from zonotope_nd.zonotope_nd import ZonotopeNd
from zonotope.utils import create_zonotope

z = create_zonotope(
    [[1, 2, 3], [1.5, 1.25, 3]], [[[0, 0], [0, 0], [0, 0]], [[0, 1], [1, 0], [0, 1]]]
)

In [22]:
from zonotope_nd.functional import tanh, exp, reciprocal

r = reciprocal(z)
r.W_C

tensor([[0.5371, 0.2588, 0.1709],
        [0.8945, 1.3320, 0.2524]], dtype=torch.float16)

In [23]:
r.W_Ei

tensor([[[-0.0000, -0.0000,  0.4629],
         [-0.0000, -0.0000,  0.2407],
         [-0.0000, -0.0000,  0.1621]],

        [[-0.0000, -0.7998,  0.3054],
         [-1.7773, -0.0000,  0.8892],
         [-0.0000, -0.2476,  0.0000]]], dtype=torch.float16)

In [18]:
rr = tanh(z)
rr.W_Ei

tensor([[[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.0000, 0.1807, 0.5029],
         [0.2808, 0.0000, 0.4609],
         [0.0000, 0.0010, 0.0168]]], dtype=torch.float16)

In [24]:
a = r.W_Ei
a[0, 0] = 2
a

tensor([[[ 2.0000,  2.0000,  2.0000],
         [-0.0000, -0.0000,  0.2407],
         [-0.0000, -0.0000,  0.1621]],

        [[-0.0000, -0.7998,  0.3054],
         [-1.7773, -0.0000,  0.8892],
         [-0.0000, -0.2476,  0.0000]]], dtype=torch.float16)

In [35]:
b = a.diagonal(dim1=-1, dim2=-2).sum(dim=[-1, -2])
b = a.diagonal(dim1=-1, dim2=-2).sum(dim=[-1])
b

tensor([2.1621, 0.0000], dtype=torch.float16)

In [29]:
c = a.sum(-1).sum(-1)

In [32]:
import torch as t

t.maximum(b - c, b + c, b - b, c - c)

TypeError: maximum() takes 2 positional arguments but 4 were given

In [39]:
a.view(-1, a.shape[-1]).shape

torch.Size([6, 3])

In [4]:
import torch as t
import einx
from einops import einsum

a = t.randn((1, 2, 3))
b = t.randn((4, 2, 5, 3))

c = einsum(a, b, "a b c, d e f c -> a b d e f")
d = einx.dot("a... c, b... c -> a... b...", a, b)
c.shape, d.shape

(torch.Size([1, 2, 4, 2, 5]), torch.Size([1, 2, 4, 2, 5]))

In [5]:
t.allclose(d, c)

True